Implement B3 propagator
honeycombio/beeline-go pull request #146
Opened 2020-09-29 07:07 UTC by Wilhansen

The Zipkin system uses B3 as their propagation protocol. This adds that feature mainly by piggybacking on the existing W3C implementation which uses otel libs.

2020-09-29 09:33 UTC, MikeGoldsmith requested changes
Thanks for the contribution @Wilhansen - this looks like a great start!

I've added one suggestion for a comment update and I think it would be good to add some tests to verify the behaviour.

2020-09-29 09:33 UTC, MikeGoldsmith commented on propagation/b3.go
> +// MarshalHoneycombTraceContext uses the information in prop to create trace context headers
```suggestion
// MarshalB3TraceContext uses the information in prop to create trace context headers
```

2020-09-29 09:54 UTC, Wilhansen commented on propagation/b3.go
> +// MarshalHoneycombTraceContext uses the information in prop to create trace context headers
Thanks for catching this!

2020-09-29 10:43 UTC, MikeGoldsmith approved these changes
Looks great - thanks!

2020-09-29 14:15 UTC, merged

2020-10-28 21:46 UTC, emorikawa commented
@Wilhansen @MikeGoldsmith, could there perhaps be an issue with the propagator. See https://github.com/honeycombio/beeline-go/issues/154

2020-10-29 00:50 UTC, Wilhansen commented
The otel 0.12 libraries still use `GetAllKeys` but their version 0.13 changed it to `Fields`:

https://github.com/open-telemetry/opentelemetry-go-contrib/commit/af2dfc7baf3392e81ea4b6938b3a8a5d39cf9db7#diff-4a74b3e6075e9b4b563e1a0768042e3829b16d15916c3976138158aab3871ccd

So I can't fix one without having to upgrade otal to 0.13, I think it goes the same for the compilation error in the w3c propagator.