Add DB.BindNamed based on Tx.BindNamed
honeycombio/beeline-go pull request #157
Opened 2020-11-02 06:29 UTC by matiasanaya

This is a straight copy from `Tx.BindNamed` so that we can access `DB.BindNamed`.

2020-11-02 14:32 UTC, MikeGoldsmith requested changes
Hi @matiasanaya - thanks for the contribution!

Please could you add a test to ensure this works as expected? We have some tests already setup [here](https://github.com/honeycombio/beeline-go/blob/main/wrappers/hnysqlx/sqlx_test.go).

Thanks

2020-11-02 23:36 UTC, matiasanaya commented
@MikeGoldsmith I've added a test now. Cheers!

2020-11-05 16:34 UTC, MikeGoldsmith approved these changes

2020-11-05 16:34 UTC, MikeGoldsmith commented
Thanks @matiasanaya 👍

2020-11-05 16:35 UTC, merged