feat: span.AddField() support adding error
honeycombio/beeline-go pull request #246
Opened 2021-07-13 13:13 UTC by llorllale

Small tweak to allow `span.AddField()` to support adding error types, similar to `beeline.AddField()`.

2021-07-13 14:43 UTC, MikeGoldsmith requested changes
Thanks for the contribution @llorllale - I like the change you've provided.

I've suggested a few small tweaks, but overall look good 👍🏻

2021-07-13 14:43 UTC, MikeGoldsmith commented on trace/trace.go
> +		if ok {
This could be simplified to:
```suggestion
		if err, ok := val.(error); ok {
```

2021-07-13 14:43 UTC, MikeGoldsmith commented on trace/trace_test.go
> +	require.True(t, ok)
I'd prefer to use the existing assert terminology:
```suggestion
	assert.Equal(t, true, ok)
```

2021-07-13 14:43 UTC, MikeGoldsmith commented on trace/trace_test.go
> +
Unnecessary whitespace
```suggestion
```

2021-07-13 14:43 UTC, MikeGoldsmith commented on trace/trace_test.go
> +	"github.com/stretchr/testify/require"
Don't require this import if we use assert as below.

```suggestion
```

2021-07-13 15:11 UTC, llorllale commented
@MikeGoldsmith applied all suggestions. I'm not sure what's wrong with the tests - I can't reproduce locally.

2021-07-13 19:44 UTC, robbkidd commented
I banged the set. (Pushed "rerun" in CI.) ✅

2021-07-16 13:24 UTC, MikeGoldsmith approved these changes
Thanks for the updates @llorllale.

2021-07-16 13:25 UTC, merged