Prep for release
honeycombio/beeline-go pull request #319
Opened 2022-04-04 12:06 UTC by kentquirk

Prep for release of 2.0.0. Requires #314 first.

2022-04-04 14:57 UTC, vreynolds commented on CHANGELOG.md
> +
```suggestion

### !!! Breaking Changes !!!

Minimum Go version required is 1.16

```

2022-04-04 14:57 UTC, vreynolds requested changes
Can we also update min Go version in Readme?

2022-04-05 16:28 UTC, vreynolds approved these changes

2022-04-05 16:30 UTC, cartermp approved these changes

2022-04-08 11:35 UTC, merged